#!/usr/bin/env bash
# worktree-codex/scripts/push_and_pr.sh
# 推送分支并在 GitHub 上创建 PR
#
# 用法: push_and_pr.sh <repo_dir> <gh_token> <github_owner_repo> <agent_name> <worktree_path> <branch> <base_branch>
# 输出: PR URL
# PR_LOG（可选环境变量）: 写入结构化标记的日志文件

set -euo pipefail

REPO_DIR="$1"
GH_TOKEN="$2"
OWNER_REPO="$3"
AGENT_NAME="$4"
WORKTREE_PATH="$5"
BRANCH="$6"
BASE_BRANCH="$7"

PR_LOG="${PR_LOG:-/tmp/pr-${AGENT_NAME}.log}"

plog() {
  local tag="$1"; shift
  echo "##${tag}## [$(date '+%H:%M:%S')] $*" | tee -a "$PR_LOG" >&2
}

plog "PR_START" "agent=$AGENT_NAME branch=$BRANCH base=$BASE_BRANCH repo=$OWNER_REPO"

cd "$WORKTREE_PATH"

# commit 摘要（让 PR 描述包含意图轨迹）
COMMIT_LOG=$(git log origin/${BASE_BRANCH}..HEAD --pretty=format:"- %s" 2>/dev/null | head -10 || echo "- (no commits ahead)")
plog "PR_COMMITS" "$COMMIT_LOG"

# RESULT 标记摘取（从 agent log 里找）
AGENT_LOG="/tmp/${AGENT_NAME}.log"
AGENT_RESULT=""
if [ -f "$AGENT_LOG" ]; then
  AGENT_RESULT=$(grep "##RESULT##" "$AGENT_LOG" | tail -1 | sed 's/.*##RESULT## \(\[.*\] \)\{0,1\}//' || echo "")
  plog "PR_AGENT_RESULT" "$AGENT_RESULT"
fi

# token 安全传递
export GIT_ASKPASS_TOKEN="$GH_TOKEN"
ASKPASS_SCRIPT=$(mktemp /tmp/git-askpass-XXXXXX.sh)
cat > "$ASKPASS_SCRIPT" << 'EOF'
#!/usr/bin/env bash
echo "$GIT_ASKPASS_TOKEN"
EOF
chmod +x "$ASKPASS_SCRIPT"

git remote set-url origin "https://github.com/${OWNER_REPO}.git"
plog "PR_PUSH_BEGIN" "branch=$BRANCH"
GIT_ASKPASS="$ASKPASS_SCRIPT" git push origin "$BRANCH" 2>&1 | tee -a "$PR_LOG" >&2
plog "PR_PUSH_DONE"  "branch=$BRANCH"
rm -f "$ASKPASS_SCRIPT"

# PR body 注入意图信息
PR_BODY=$(printf "## %s — Agent Output\n\n**任务结果：** %s\n\n**Commits：**\n%s\n\n---\n*Generated by OpenClaw worktree-codex*\nWorktree: \`%s\`  Branch: \`%s\`" \
  "$AGENT_NAME" \
  "${AGENT_RESULT:-（无 RESULT 标记）}" \
  "$COMMIT_LOG" \
  "$WORKTREE_PATH" \
  "$BRANCH")

plog "PR_CREATE_BEGIN" "title=[$AGENT_NAME] automated task"
RESPONSE=$(curl -s -X POST \
  -H "Authorization: Bearer $GH_TOKEN" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/$OWNER_REPO/pulls" \
  -d "$(jq -n \
    --arg title "[$AGENT_NAME] automated task" \
    --arg head "$BRANCH" \
    --arg base "$BASE_BRANCH" \
    --arg body "$PR_BODY" \
    '{title: $title, head: $head, base: $base, body: $body}')")

PR_URL=$(echo "$RESPONSE" | jq -r '.html_url // empty')

if [ -z "$PR_URL" ]; then
  plog "PR_CREATE_FAILED" "$(echo "$RESPONSE" | head -c 200)"
  echo "[ERROR] PR 创建失败，API 返回：" >&2
  echo "$RESPONSE" >&2
  exit 1
fi

plog "PR_CREATE_DONE" "url=$PR_URL"
echo "$PR_URL"

